name: mmgis
channels:
  - conda-forge
dependencies:
  - python==3.12
  - gdal==3.9.3
  - rasterio
  - geos
  - proj
  - pip
  - pip:
      - numpy==2.1.0
      - requests==2.32.3
      - rio_stac==0.8.1
      - spiceypy==5.1.2
      - pymap3d==3.0.1
      - pypgstac==0.9.6
      - python-dotenv[cli]==1.0.1
      - uvicorn==0.30.6
      - psycopg[binary,pool]==3.2.1
      - stac-fastapi-pgstac==5.0.2
      - tipg==1.1.0
      - titiler.application==0.22.2
      - titiler-pgstac==1.8.0
