#Simple Makefile to package the python as a tar.gz archive with version formatting similar to the maven project.
#At this time, versioning must be updated manually.

AMMOS_VER=30.02.000
KMC_VER=3.0.0
SDLS_CLIENT_VER=0.1.0
BUILD_NUM=0
OS=RHEL7

ARTIFACTS = src README.rst setup.py makefile

all: clean uninstall install artifact

install:
	python setup.py install --user

uninstall:
	yes | pip uninstall SdlsClient

artifact:
	mkdir -p dist
	tar -czvf dist/MGSS-AMMOS-$(AMMOS_VER)-KMC-$(KMC_VER)-B$(BUILD_NUM)-$(OS)-64_Bit_kmc-python-sdls-client-$(SDLS_CLIENT_VER)b$(BUILD_NUM).tar.gz $(ARTIFACTS)

clean:
	rm -rf dist build *.egg-info __pycache__